image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
java -Duser.language=en -Duser.country=US -jar app-mbank.jar

build_script:
  - ./gradlew test --info chmod +x gradlew # запускаем тест, флаг --info позволяет выводить больше информации